# Matrix calculation with Numpy

## 1. Resumen

This notebook has been automatically translated to make it accessible to more people, please let me know if you see any typos.

We are going to see a small introduction to the matrix calculation library `Numpy`. This library is designed for all types of matrix calculus, so we are going to stay only with the part that will be useful to understand the calculations inside the neural networks, but we will leave out interesting things like the use of the library for linear algebra.


<p align="center">
  <img src="https://github.com/DeepMaxFN/DeepMaxFN-blog/blob/master/images/numpy-icon.png?raw=true">
</p>

## What is Numpy?

Numpy is a Python library designed to perform matrix computation. Matrix computation is something that is used a lot in science in general and data science in particular, so it is necessary to have a library that does this very well.

Its name stands for numerical python

Its main object is the `ndarray`, which encapsulates `n` dimension arrays of homogeneous data types, unlike Python lists that can have data of different types.

Numpy aims to perform matrix computation much faster than with Python lists, but how is this possible?

* Numpy uses compiled code, while Python uses interpreted code. The difference is that Python at runtime has to interpret, compile and execute the code, while in Numpy it is already compiled, so it runs faster.
* The `ndarray`s have a fixed size, unlike the Python lists that are dynamic. If in Numpy you want to modify the size of an array, a new one will be created and the old one will be deleted.
* All elements of the `ndarray`s are of the same data type, unlike Python lists that can have elements of different types.
* Part of the Numpy code is written in C/C++ (much faster than Python).
* Array data is stored in memory continuously, unlike Python lists, which makes it much faster to manipulate it.

Numpy offers the facility of using code that is simple to write and read, but is written and precompiled in C, which makes it much faster.
 
Suppose we want to multiply two vectors, this would be done in C in the following way
 
```c
for (i = 0; i < rows; i++): {
  for (j = 0; j < columns; j++): {
    c[i][j] = a[i][j]*b[i][j];
  }
}
```
 
Numpy offers the possibility of executing this code underneath, but much easier to write and understand by means of
 
``python
c = a * b
```

Numpy offers vectorized code, which means not having to write loops, but nevertheless if they are being executed underneath in optimized and precompiled C code. This has the following advantages:

* The code is easier to write and read.
* Fewer lines of code mean fewer errors are likely to be introduced.
* The code looks more like mathematical notation.

### 2.1. Numpy as `np`.

Generally when importing Numpy it is usually imported with the alias `np`.

In [1]:
import numpy as np

print(np.__version__)

1.18.1


## 3. Numpy speed

As explained Numpy performs the calculation much faster than Python lists, let's see an example in which the scalar product of two matrices is performed, using Python lists and using `ndarray`s

In [2]:
from time import time
 
# Dimensión de las matrices
dim = 1000
shape = (dim, dim)
 
# Se crean dos ndarrays de Numpy de dimensión dim x dim
ndarray_a = np.ones(shape=shape)
ndarray_b = np.ones(shape=shape)
 
# Se crean dos listas de Python de dimensión dim x dim a partir de los ndarrays
list_a = list(ndarray_a)
list_b = list(ndarray_b)
 
# Se crean el ndarray y la lista de Python donde se guardarán los resultados
ndarray_c = np.empty(shape=shape)
list_c = list(ndarray_c)
 
# Producto escalar de dos listas de python
t0 = time()
for fila in range(dim):
  for columna in range(dim):
    list_c[fila][columna] = list_a[fila][columna] * list_b[fila][columna]
t = time()
t_listas = t-t0
print(f"Tiempo para realizar el producto escalar de dos listas de Python de dimensiones {dim}x{dim}: {t_listas:.4f} ms")
 
 
# Producto escalar de dos ndarrays de Numpy
t0 = time()
ndarray_c = ndarray_a * ndarray_b
t = time()
t_ndarrays = t-t0
print(f"Tiempo para realizar el producto escalar de dos ndarrays de Numpy de dimensiones {dim}x{dim}: {t_ndarrays:.4f} ms")
 
# Comparación de tiempos
print(f"\nHacer el cálculo con listas de Python tarda {t_listas/t_ndarrays:.2f} veces más rápido que con ndarrays de Numpy")

Tiempo para realizar el producto escalar de dos listas de Python de dimensiones 1000x1000: 0.5234 ms
Tiempo para realizar el producto escalar de dos ndarrays de Numpy de dimensiones 1000x1000: 0.0017 ms

Hacer el cálculo con listas de Python tarda 316.66 veces más rápido que con ndarrays de Numpy


## 4. Matrices in Numpy

In Numpy an array is an `ndarray` object.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


### 4.1. How to create matrices

With the `array()` method you can create `ndarray`s by entering Python lists (as the example above), or tuples

In [ ]:
arr = np.array((1, 2, 3, 4, 5))

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


With the `zeros()` method you can create arrays filled with zeros.

In [3]:
arr = np.zeros((3, 4))

print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


The `zeros_like(A)` method returns an array with the same shape as the array A, but filled with zeros.

In [ ]:
A = np.array((1, 2, 3, 4, 5))
arr = np.zeros_like(A)

print(arr)

[0 0 0 0 0]


With the `ones()` method it is possible to create arrays filled with ones

In [ ]:
arr = np.ones((4, 3))

print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


The `ones_like(A)` method returns an array with the same shape as the array A, but filled with zeros.

In [ ]:
A = np.array((1, 2, 3, 4, 5))
arr = np.ones_like(A)

print(arr)

[1 1 1 1 1]


With the `empty()` method you can create arrays with the dimensions you want, but randomly initialized.

In [ ]:
arr = np.empty((6, 3))

print(arr)

[[4.66169180e-310 2.35541533e-312 2.41907520e-312]
 [2.14321575e-312 2.46151512e-312 2.31297541e-312]
 [2.35541533e-312 2.05833592e-312 2.22809558e-312]
 [2.56761491e-312 2.48273508e-312 2.05833592e-312]
 [2.05833592e-312 2.29175545e-312 2.07955588e-312]
 [2.14321575e-312 0.00000000e+000 0.00000000e+000]]


The `empty_like(A)` method returns an array with the same shape as the array A, but randomly initialized.

In [ ]:
A = np.array((1, 2, 3, 4, 5))
arr = np.empty_like(A)

print(arr)

[4607182418800017408 4611686018427387904 4613937818241073152
 4616189618054758400 4617315517961601024]


With the `arange(start, stop, step)` method you can create arrays in a given range. This method is similar to Python's `range()` method.

In [ ]:
arr = np.arange(10, 30, 5)

print(arr)

[10 15 20 25]


When `arange` is used with floating point arguments, it is generally not possible to predict the number of elements obtained, because floating point precision is finite.

For this reason, it is usually better to use the `linspace(start, stop, n)` function that receives as argument the number of elements we want, instead of the `linspace(start, stop, n)` step

In [ ]:
arr = np.linspace(0, 2, 9)
 
print(arr)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


Finally, if we want to create arrays with random numbers we can use the `random.rand` function with a tuple with the dimensions as a parameter

In [8]:
arr = np.random.rand(2, 3)

print(arr)

[[0.32726085 0.65571767 0.73126697]
 [0.91938206 0.9862451  0.95033649]]


### 4.2. Matrix dimensions

In Numpy we can create arrays of any dimension. To get the dimension of an array we use the `ndim` method

Matrix of dimension 0, which would be equivalent to one number

In [ ]:
arr = np.array(42)

print(arr)
print(arr.ndim)

42
0


Matrix of dimension 1, which would be equivalent to a vector

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(arr.ndim)

[1 2 3 4 5]
1


Matrix of dimension 2, which is equivalent to a matrix of dimension 2, which is equivalent to a matrix of dimension 2, which is equivalent to a matrix of dimension 3.

In [ ]:
arr = np.array([[1, 2, 3, 4, 5], 
                [6, 7, 8, 9, 10]])

print(arr)
print(arr.ndim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2


Dimension 3 matrix

In [ ]:
arr = np.array([
                [[1, 2, 3, 4, 5], 
                [6, 7, 8, 9, 10]],
                
                [[11, 12, 13, 14, 15], 
                [16, 17, 18, 19, 20]]
                ])

print(arr)
print(arr.ndim)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
3


Array of dimension N. When creating `ndarray`s, the number of dimensions can be set by means of the `ndim` parameter

In [ ]:
arr = np.array([1, 2, 3, 4, 5], ndmin=6)

print(arr)
print(arr.ndim)

[[[[[[1 2 3 4 5]]]]]]
6


### 4.3. Size of the matrices

If instead of the dimension of the guideline, we want to see the size of the guideline, we can use the `shape` method

In [2]:
arr = np.array([
                [[1, 2, 3, 4, 5], 
                [6, 7, 8, 9, 10]],
                
                [[11, 12, 13, 14, 15], 
                [16, 17, 18, 19, 20]]
                ])

print(arr.shape)

(2, 2, 5)


## Data type

The data that Numpy arrays can store are as follows:


* `i` - Entero
* 'b' - Booleano
* `u` - Unsigned integer
* `f` - Floating
* `c` - Floating complex
* `m` - Timedelta
* `M` - Datetime
* `O` - Object
* `S` - String
* `U` - Unicode string
* `V` - Fixed memory fragment for another type (void)

We can check the data type of an array using `dtype`.

In [ ]:
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

int64
<U6


We can also create arrays by indicating the type of data we want it to have through `dtype`.

In [ ]:
arr = np.array([1, 2, 3, 4], dtype='i')
print("Enteros:")
print(arr)
print(arr.dtype)
 
arr = np.array([1, 2, 3, 4], dtype='f')
print("\nFloat:")
print(arr)
print(arr.dtype)
 
arr = np.array([1, 2, 3, 4], dtype='f')
print("\nComplejos:")
print(arr)
print(arr.dtype)
 
arr = np.array([1, 2, 3, 4], dtype='S')
print("\nString:")
print(arr)
print(arr.dtype)
 
arr = np.array([1, 2, 3, 4], dtype='U')
print("\nUnicode string:")
print(arr)
print(arr.dtype)
 
arr = np.array([1, 2, 3, 4], dtype='O')
print("\nObjeto:")
print(arr)
print(arr.dtype)

Enteros:
[1 2 3 4]
int32

Float:
[1. 2. 3. 4.]
float32

Complejos:
[1. 2. 3. 4.]
float32

String:
[b'1' b'2' b'3' b'4']
|S1

Unicode string:
['1' '2' '3' '4']
<U1

Objeto:
[1 2 3 4]
object


## 6. Mathematical operations

### 6.1. Basic operations

Matrix operations are performed by elements, for example, if we add two matrices, the elements of each matrix of the same position will be added, as is done in the mathematical addition of two matrices.

In [ ]:
A = np.array([1, 2, 3])
B = np.array([1, 2, 3])

print(f"Matriz A: tamaño {A.shape}\n{A}\n")
print(f"Matriz B: tamaño {B.shape}\n{B}\n")

C = A + B
print(f"Matriz C: tamaño {C.shape}\n{C}\n")

D = A - B
print(f"Matriz D: tamaño {D.shape}\n{D}")

Matriz A: tamaño (3,)
[1 2 3]

Matriz B: tamaño (3,)
[1 2 3]

Matriz C: tamaño (3,)
[2 4 6]

Matriz D: tamaño (3,)
[0 0 0]


However, if we multiply two matrices, we also multiply each element of the matrices (scalar product).

In [ ]:
A = np.array([[3, 5], [4, 1]])
B = np.array([[1, 2], [-3, 0]])
 
print(f"Matriz A: tamaño {A.shape}\n{A}\n")
print(f"Matriz B: tamaño {B.shape}\n{B}\n")
 
C = A * B
print(f"Matriz C: tamaño {C.shape}\n{C}\n")

Matriz A: tamaño (2, 2)
[[3 5]
 [4 1]]

Matriz B: tamaño (2, 2)
[[ 1  2]
 [-3  0]]

Matriz C: tamaño (2, 2)
[[  3  10]
 [-12   0]]



To make the matrix product that has been taught in mathematics all your life you have to use the operator `@` or the `dot` method.

In [ ]:
A = np.array([[3, 5], [4, 1], [6, -1]])
B = np.array([[1, 2, 3], [-3, 0, 4]])

print(f"Matriz A: tamaño {A.shape}\n{A}\n")
print(f"Matriz B: tamaño {B.shape}\n{B}\n")

C = A @ B
print(f"Matriz C: tamaño {C.shape}\n{C}\n")

D = A.dot(B)
print(f"Matriz D: tamaño {D.shape}\n{D}")

Matriz A: tamaño (3, 2)
[[ 3  5]
 [ 4  1]
 [ 6 -1]]

Matriz B: tamaño (2, 3)
[[ 1  2  3]
 [-3  0  4]]

Matriz C: tamaño (3, 3)
[[-12   6  29]
 [  1   8  16]
 [  9  12  14]]

Matriz D: tamaño (3, 3)
[[-12   6  29]
 [  1   8  16]
 [  9  12  14]]


If instead of creating a new matrix, you want to modify an existing one, you can use the `+=`, `-=` or `*=` switches.

In [ ]:
A = np.array([[3, 5], [4, 1]])
B = np.array([[1, 2], [-3, 0]])

print(f"Matriz A: tamaño {A.shape}\n{A}\n")
print(f"Matriz B: tamaño {B.shape}\n{B}\n")

A += B
print(f"Matriz A tras suma: tamaño {A.shape}\n{A}\n")

A -= B
print(f"Matriz A tras resta: tamaño {A.shape}\n{A}\n")

A *= B
print(f"Matriz A tras multiplicación: tamaño {A.shape}\n{A}\n")

Matriz A: tamaño (2, 2)
[[3 5]
 [4 1]]

Matriz B: tamaño (2, 2)
[[ 1  2]
 [-3  0]]

Matriz A tras suma: tamaño (2, 2)
[[4 7]
 [1 1]]

Matriz A tras resta: tamaño (2, 2)
[[3 5]
 [4 1]]

Matriz A tras multiplicación: tamaño (2, 2)
[[  3  10]
 [-12   0]]



It is possible to perform operations on all the elements of an array, this is thanks to a property called `brodcasting` that we will see later in more depth

In [ ]:
A = np.array([[3, 5], [4, 1]])
 
print(f"Matriz A: tamaño {A.shape}\n{A}\n")
 
B = A * 2
print(f"Matriz B: tamaño {B.shape}\n{B}\n")
 
C = A ** 2
print(f"Matriz C: tamaño {C.shape}\n{C}\n")
 
D = 2*np.sin(A)
print(f"Matriz D: tamaño {D.shape}\n{D}")

Matriz A: tamaño (2, 2)
[[3 5]
 [4 1]]

Matriz B: tamaño (2, 2)
[[ 6 10]
 [ 8  2]]

Matriz C: tamaño (2, 2)
[[ 9 25]
 [16  1]]

Matriz D: tamaño (2, 2)
[[ 0.28224002 -1.91784855]
 [-1.51360499  1.68294197]]


### 6.2. Functions on matrices

As you can see in the last calculation, Numpy offers function operators on matrices, there are a lot of [functions](https://numpy.org/doc/stable/reference/routines.html) that can be performed on matrices, mathematical, logical, linear algebra, etc. Here are some of them

In [ ]:
A = np.array([[3, 5], [4, 1]])

print(f"A\n{A}\n")

print(f"exp(A)\n{np.exp(A)}\n")
print(f"sqrt(A)\n{np.sqrt(A)}\n")
print(f"cos(A)\n{np.cos(A)}\n")

A
[[3 5]
 [4 1]]

exp(A)
[[ 20.08553692 148.4131591 ]
 [ 54.59815003   2.71828183]]

sqrt(A)
[[1.73205081 2.23606798]
 [2.         1.        ]]

cos(A)
[[-0.9899925   0.28366219]
 [-0.65364362  0.54030231]]



There are some functions that return information from the matrices, such as the average

In [ ]:
A = np.array([[3, 5], [4, 1]])

print(f"A\n{A}\n")

print(f"A.mean()\n{A.mean()}\n")

A
[[3 5]
 [4 1]]

A.mean()
3.25



However, we can obtain this information for each axis by means of the `axis` attribute, if this is 0 it is done on each column, while if it is 1 it is done on each row.

In [ ]:
A = np.array([[3, 5], [4, 1]])
 
print(f"A\n{A}\n")
 
print(f"A.mean() columnas\n{A.mean(axis=0)}\n")
print(f"A.mean() filas\n{A.mean(axis=1)}\n")

A
[[3 5]
 [4 1]]

A.mean() columnas
[3.5 3. ]

A.mean() filas
[4.  2.5]



### 6.3. Broadcasting

Matrix operations can be performed with matrices of different dimensions. In this case Numpy will detect this and make a projection of the smaller matrix until it equals the larger one.

![numpy_broadcasting](https://raw.githubusercontent.com/DeepMaxFN/DeepMaxFN-blog/master/images/numpy_broadcasting.png)

This is a great quality of Numpy, which makes it possible to perform calculations on matrices without having to worry about matching their dimensions.

In [ ]:
A = np.array([1, 2, 3])

print(f"A\n{A}\n")

B = A + 5

print(f"B\n{B}\n")

A
[1 2 3]

B
[6 7 8]



In [ ]:
A = np.array([1, 2, 3])
B = np.ones((3,3))

print(f"A\n{A}\n")
print(f"B\n{B}\n")

C = A + B

print(f"C\n{C}\n")

A
[1 2 3]

B
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

C
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]



In [ ]:
A = np.array([1, 2, 3])
B = np.array([[1], [2], [3]])
 
print(f"A\n{A}\n")
print(f"B\n{B}\n")
 
C = A + B
 
print(f"C\n{C}\n")

A
[1 2 3]

B
[[1]
 [2]
 [3]]

C
[[2 3 4]
 [3 4 5]
 [4 5 6]]



## 7. Matrix indexing

The indexing of arrays is done in the same way as with Python lists.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr[3]

4

In the case of having more than one dimension, the index must be indicated in each one of them.

In [ ]:
arr = np.array([[1, 2, 3, 4, 5], 
                [6, 7, 8, 9, 10]])
arr[1, 2]

8

Negative indexing can be used

In [ ]:
arr[-1, -2]

9

If you do not indicate one of the axes, it is considered that you want an integer.

In [ ]:
arr = np.array([[1, 2, 3, 4, 5], 
                [6, 7, 8, 9, 10]])
arr[1]

array([ 6,  7,  8,  9, 10])

### 7.1. Portions of matrices

When indexing we can keep parts of arrays just as we used to do with Python lists.

Remember that it was done as follows:

`start:stop:step`

Where the range goes from `start` (included) to `stop` (not included) with a step of `step`.

If `step` is not specified default is 1

For example, if we want items from the second row and from the second to the fourth column:

* We select the second row with a 1 (since we start counting from 0).
* We select from the second to the fourth row using 1:4, the 1 to indicate the second column and the 4 to indicate the fifth (since the second number indicates the column in which it ends without including this column). The two numbers taking into account that we start counting from 0

In [ ]:
print(arr)
print(arr[1, 1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[7 8 9]


We can take from one position to the end

In [ ]:
arr[1, 2:]

array([ 8,  9, 10])

From the beginning to a position

In [ ]:
arr[1, :3]

array([6, 7, 8])

Set the range with negative numbers

In [ ]:
arr[1, -3:-1]

array([8, 9])

Choose the step

In [ ]:
arr[1, 1:4:2]

array([7, 9])

### 7.2. Iteraction on matrices

The iteration over multidimensional matrices is performed with respect to the first axis

In [ ]:
M = np.array( [[[  0,  1,  2],
                [ 10, 12, 13]],
               [[100,101,102],
                [110,112,113]]])

print(f'Matriz de dimensión: {M.shape}\n')

i = 0
for fila in M:
  print(f'Fila {i}: {fila}')
  i += 1

Matriz de dimensión: (2, 2, 3)

Fila 0: [[ 0  1  2]
 [10 12 13]]
Fila 1: [[100 101 102]
 [110 112 113]]


However, if we want to iterate for each item we can use the 'flat' method

In [ ]:
i = 0
for fila in M.flat:
  print(f'Elemento {i}: {fila}')
  i += 1

Elemento 0: 0
Elemento 1: 1
Elemento 2: 2
Elemento 3: 10
Elemento 4: 12
Elemento 5: 13
Elemento 6: 100
Elemento 7: 101
Elemento 8: 102
Elemento 9: 110
Elemento 10: 112
Elemento 11: 113


## 8. Matrix copying

In Numpy we have two ways to copy arrays, by `copy`, which makes a new copy of the array, and by `view` which makes a view of the original array.
 
The copy owns the data and any changes made to the copy will not affect the original matrix, and any changes made to the original matrix will not affect the copy.
 
The view does not own the data and any changes made to the copy will affect the original matrix, and any changes made to the original matrix will affect the copy.

### 8.1. Copy

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
copy_arr = arr.copy()
arr[0] = 42
copy_arr[1] = 43
 
print(f'Original: {arr}')
print(f'Copia:    {copy_arr}')

Original: [42  2  3  4  5]
Copia:    [ 1 43  3  4  5]


### 8.2. View

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
view_arr = arr.view()
arr[0] = 42
view_arr[1] = 43
 
print(f'Original: {arr}')
print(f'Vista:    {view_arr}')

Original: [42 43  3  4  5]
Vista:    [42 43  3  4  5]


### 8.3. Data owner

When in doubt whether we have a copy or a view we can use `base`.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
 
copy_arr = arr.copy()
view_arr = arr.view()
 
print(copy_arr.base)
print(view_arr.base)

None
[1 2 3 4 5]


## 9. Form of the matrices

We can know the shape of the array using the `shape` method. This will return a tuple, the size of the tuple represents the dimensions of the array, in each element of the tuple the number of items in each of the dimensions of the array is indicated.

In [ ]:
arr = np.array([
                [[1, 2, 3, 4, 5], 
                [6, 7, 8, 9, 10]],
                
                [[11, 12, 13, 14, 15], 
                [16, 17, 18, 19, 20]]
                ])
 
print(arr)
print(arr.shape)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
(2, 2, 5)


### 9.1. Reshape

We can change the shape of the matrices to the one we want using the `reshape` method.

For example, the matrix above, which has a form of `(2, 2, 4)`. We can pass it to `(5, 4)`.

In [ ]:
arr_reshape = arr.reshape(5, 4)

print(arr_reshape)
print(arr_reshape.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
(5, 4)


Note that to resize the matrices, the number of items in the new form must have the same number of items as in the first form.

That is, in the previous example, the first matrix had 20 items (2x2x4), and the new matrix has 20 items (5x4). What we cannot do is to resize it to a matrix of size (3, 4), since there would be a total of 12 items.

In [ ]:
arr_reshape = arr.reshape(3, 4)

ValueError: ignored

### 9.2. Unknown dimension

In case we want to change the shape of a matrix and one of the dimensions is unknown to us, we can have Numpy calculate it for us by entering a `-1` as a parameter

In [ ]:
arr = np.array([
                [[1, 2, 3, 4, 5], 
                [6, 7, 8, 9, 10]],
                
                [[11, 12, 13, 14, 15], 
                [16, 17, 18, 19, 20]]
                ])

arr_reshape = arr.reshape(2, -1)

print(arr_reshape)
print(arr_reshape.shape)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
(2, 10)


Note that you cannot put just any number in the known dimensions. The number of items in the original matrix must be a multiple of the known dimensions.

In the above example, the matrix has 20 items, which is a multiple of 2, the known dimension entered. It would not have been possible to put a 3 as the known dimension, since 20 is not a multiple of 3, and there would be no number that could be put in the unknown dimension that would make a total of 20 items.

### 9.3. Matrix flattening

We can flatten the matrices, that is, pass them to a single dimension by `reshape(-1)`. In this way, whatever the dimensions of the original matrix, the new one will always have only one dimension.

In [ ]:
arr = np.array([
                [[1, 2, 3, 4, 5], 
                [6, 7, 8, 9, 10]],
                
                [[11, 12, 13, 14, 15], 
                [16, 17, 18, 19, 20]]
                ])

arr_flatten = arr.reshape(-1)

print(arr_flatten)
print(arr_flatten.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
(20,)


Another way to flatten a matrix is by using the `ravel()` method.

In [ ]:
arr = np.array([
                [[1, 2, 3, 4, 5], 
                [6, 7, 8, 9, 10]],
                
                [[11, 12, 13, 14, 15], 
                [16, 17, 18, 19, 20]]
                ])

arr_flatten = arr.ravel()

print(arr_flatten)
print(arr_flatten.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
(20,)


### 9.4. Transposed matrix

The transpose of a matrix can be obtained using the `T` method. To do the transpose of a matrix is to interchange the rows and columns of the matrix, in the following image you can see an example that clarifies it more clearly

![transpose_matrix](https://github.com/DeepMaxFN/DeepMaxFN-blog/blob/master/images/Transpose_matrix.png?raw=true)

In [ ]:
arr = np.array([[1, 0, 4], 
                [0, 5, 0],
                [6, 0, -9]])
 
arr_t = arr.T
 
print(arr_t)
print(arr_t.shape)

[[ 1  0  6]
 [ 0  5  0]
 [ 4  0 -9]]
(3, 3)


## 10. Matrix Stacking

### 10.1. Vertical stacking

Matricecs can be stacked vertically (joining rows) using the `vstack()` method.

In [ ]:
a = np.array([[1, 1, 1], 
              [2, 2, 2],
              [3, 3, 3]])

b = np.array([[4, 4, 4], 
              [5, 5, 5],
              [6, 6, 6]])

c = np.vstack((a,b))
c

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4],
       [5, 5, 5],
       [6, 6, 6]])

If you have arrays of more than 2 dimensions `vsatck()` will stack along the first dimension.

In [ ]:
a = np.array([
                [[1, 1], 
                [2, 2]],
                
                [[3, 3], 
                [4, 4]]
                ])
 
b = np.array([
                [[5, 5], 
                [6, 6]],
                
                [[7, 7], 
                [8, 8]]
                ])
 
c = np.vstack((a,b))
c

array([[[1, 1],
        [2, 2]],

       [[3, 3],
        [4, 4]],

       [[5, 5],
        [6, 6]],

       [[7, 7],
        [8, 8]]])

### 10.2. Horizontal stacking

You can stack matrices horizontally (joining columns) using the `hstack()` method.

In [ ]:
a = np.array([[1, 2, 3], 
              [1, 2, 3],
              [1, 2, 3]])

b = np.array([[4, 5, 6], 
              [4, 5, 6],
              [4, 5, 6]])

c = np.hstack((a,b))
c

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

If you have arrays of more than 2 dimensions `hsatck()` will stack along the second dimension.

In [ ]:
a = np.array([
                [[1, 1], 
                [2, 2]],
                
                [[3, 3], 
                [4, 4]]
                ])

b = np.array([
                [[5, 5], 
                [6, 6]],
                
                [[7, 7], 
                [8, 8]]
                ])

c = np.hstack((a,b))
c

array([[[1, 1],
        [2, 2],
        [5, 5],
        [6, 6]],

       [[3, 3],
        [4, 4],
        [7, 7],
        [8, 8]]])

Another way to add columns to a matrix is by using the `column_stack()` method.

In [ ]:
a = np.array([[1, 2, 3], 
              [1, 2, 3],
              [1, 2, 3]])
 
b = np.array([4, 4, 4])
 
c = np.column_stack((a,b))
c

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

### 10.3. Deep stacking

Arrays can be stacked in depth (third dimension) using the `dstack()` method.

In [ ]:
a = np.array([
                [[1, 1], 
                [2, 2]],
                
                [[3, 3], 
                [4, 4]]
                ])

b = np.array([
                [[1, 1], 
                [2, 2]],
                
                [[3, 3], 
                [4, 4]]
                ])

c = np.dstack((a,b))
print(f"c: {c}\n")
print(f"a.shape: {a.shape}, b.shape: {b.shape}, c.shape: {c.shape}")

c: [[[1 1 1 1]
  [2 2 2 2]]

 [[3 3 3 3]
  [4 4 4 4]]]

a.shape: (2, 2, 2), b.shape: (2, 2, 2), c.shape: (2, 2, 4)


If you have arrays of more than 4 dimensions `dsatck()` will stack along the third dimension.

In [ ]:
a = np.array([1, 2, 3, 4, 5], ndmin=4)

b = np.array([1, 2, 3, 4, 5], ndmin=4)

c = np.dstack((a,b))
print(f"a.shape: {a.shape}, b.shape: {b.shape}, c.shape: {c.shape}")

a.shape: (1, 1, 1, 5), b.shape: (1, 1, 1, 5), c.shape: (1, 1, 2, 5)


### 10.3. Custom stacking

Using the `concatenate()` method you can choose the axis on which you want to stack the arrays

In [ ]:
a = np.array([
                [[1, 1], 
                [2, 2]],
                
                [[3, 3], 
                [4, 4]]
                ])

b = np.array([
                [[5, 5], 
                [6, 6]],
                
                [[7, 7], 
                [8, 8]]
                ])

conc0 = np.concatenate((a,b), axis=0) # concatenamiento en el primer eje
conc1 = np.concatenate((a,b), axis=1) # concatenamiento en el segundo eje
conc2 = np.concatenate((a,b), axis=2) # concatenamiento en el tercer eje
print(f"conc0: {conc0}\n")
print(f"conc1: {conc1}\n")
print(f"conc2: {conc2}")

conc0: [[[1 1]
  [2 2]]

 [[3 3]
  [4 4]]

 [[5 5]
  [6 6]]

 [[7 7]
  [8 8]]]

conc1: [[[1 1]
  [2 2]
  [5 5]
  [6 6]]

 [[3 3]
  [4 4]
  [7 7]
  [8 8]]]

conc2: [[[1 1 5 5]
  [2 2 6 6]]

 [[3 3 7 7]
  [4 4 8 8]]]


## 11. Dividing matrices

### 11.1. Dividing vertically

Matricecs can be split vertically (by separating rows) using the `vsplit()` method.

In [ ]:
a = np.array([[1.1, 1.2, 1.3, 1.4], 
              [2.1, 2.2, 2.3, 2.4],
              [3.1, 3.2, 3.3, 3.4],
              [4.1, 4.2, 4.3, 4.4]])

[a1, a2] = np.vsplit(a, 2)
print(f"a1: {a1}\n")
print(f"a2: {a2}")

a1: [[1.1 1.2 1.3 1.4]
 [2.1 2.2 2.3 2.4]]

a2: [[3.1 3.2 3.3 3.4]
 [4.1 4.2 4.3 4.4]]


If you have matrices of more than 2 dimensions `vsplit()` will divide along the first dimension.

In [ ]:
a = np.array([
                [[1, 1], 
                [2, 2]],
                
                [[3, 3], 
                [4, 4]]
                ])

[a1, a2] = np.vsplit(a, 2)
print(f"a1: {a1}\n")
print(f"a2: {a2}")

a1: [[[1 1]
  [2 2]]]

a2: [[[3 3]
  [4 4]]]


### 11.2. Divide horizontally

You can split matrices horizontally (separating columns) using the `hsplit()` method.

In [ ]:
a = np.array([[1.1, 1.2, 1.3, 1.4], 
              [2.1, 2.2, 2.3, 2.4],
              [3.1, 3.2, 3.3, 3.4],
              [4.1, 4.2, 4.3, 4.4]])

[a1, a2] = np.hsplit(a, 2)
print(f"a1: {a1}\n")
print(f"a2: {a2}")

a1: [[1.1 1.2]
 [2.1 2.2]
 [3.1 3.2]
 [4.1 4.2]]

a2: [[1.3 1.4]
 [2.3 2.4]
 [3.3 3.4]
 [4.3 4.4]]


If you have matrices of more than 2 dimensions `hsplit()` will divide along the second dimension.

In [ ]:
a = np.array([
                [[1, 1], 
                [2, 2]],
                
                [[3, 3], 
                [4, 4]]
                ])

[a1, a2] = np.hsplit(a, 2)
print(f"a1: {a1}\n")
print(f"a2: {a2}")

a1: [[[1 1]]

 [[3 3]]]

a2: [[[2 2]]

 [[4 4]]]


### 11.3. Custom splitting

By means of the `array_split()` method you can choose the axis on which you want to split the arrays

In [ ]:
a = np.array([
                [[1, 1], 
                [2, 2]],
                
                [[3, 3], 
                [4, 4]]
                ])

[a1_eje0, a2_eje0] = np.array_split(a, 2, axis=0)
[a1_eje1, a2_eje1] = np.array_split(a, 2, axis=1)
[a1_eje2, a2_eje2] = np.array_split(a, 2, axis=2)

print(f"a1_eje0: {a1_eje0}\n")
print(f"a2_eje0: {a2_eje0}\n\n")

print(f"a1_eje1: {a1_eje1}\n")
print(f"a2_eje1: {a2_eje1}\n\n")

print(f"a1_eje2: {a1_eje2}\n")
print(f"a2_eje2: {a2_eje2}")

a1_eje0: [[[1 1]
  [2 2]]]

a2_eje0: [[[3 3]
  [4 4]]]


a1_eje1: [[[1 1]]

 [[3 3]]]

a2_eje1: [[[2 2]]

 [[4 4]]]


a1_eje2: [[[1]
  [2]]

 [[3]
  [4]]]

a2_eje2: [[[1]
  [2]]

 [[3]
  [4]]]


## 12. Search in matrices

If you want to search for a value within an array you can use the `where()` method which returns the positions where the array is worth the value you are looking for.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

ids = np.where(arr == 4)
ids

(array([3, 5, 6]),)

You can use functions to search, for example, if you want to search in which positions the values are pairs

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

ids = np.where(arr%2)
ids

(array([0, 2, 4, 6]),)

## 13. Order matrices

By means of the `sort()` method we can sort arrays

In [ ]:
arr = np.array([3, 2, 0, 1])

arr_ordenado = np.sort(arr)
arr_ordenado

array([0, 1, 2, 3])

If what we have are strings, it sorts them alphabetically

In [ ]:
arr = np.array(['banana', 'apple', 'cherry'])

arr_ordenado = np.sort(arr)
arr_ordenado

array(['apple', 'banana', 'cherry'], dtype='<U6')

And the Boolean arrays are also sorted by

In [ ]:
arr = np.array([True, False, True])

arr_ordenado = np.sort(arr)
arr_ordenado

array([False,  True,  True])

If you have matrices of more than one dimension, it orders them by dimensions, that is, if you have a 2-dimensional matrix, it orders the numbers of the first row among them and those of the second row among them.

In [ ]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

arr_ordenado = np.sort(arr)
arr_ordenado

array([[2, 3, 4],
       [0, 1, 5]])

By default it always sorts with respect to rows, but if you want it to sort with respect to another dimension, you have to specify it with the variable `axis`.

In [ ]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

arr_ordenado0 = np.sort(arr, axis=0) # Se ordena con respecto a la primera dimensión
arr_ordenado1 = np.sort(arr, axis=1) # Se ordena con respecto a la segunda dimensión

print(f"arr_ordenado0: {arr_ordenado0}\n")
print(f"arr_ordenado1: {arr_ordenado1}\n")

arr_ordenado0: [[3 0 1]
 [5 2 4]]

arr_ordenado1: [[2 3 4]
 [0 1 5]]



## 14. Filters in matrices

Numpy offers the ability to search for certain elements of an array and create a new one.

This is done by creating an array of Boolean indexes, i.e., it creates a new array that indicates which positions in the array we keep and which we do not keep.

Let's see an example of a Boolean index array

In [ ]:
arr = np.array([37, 85, 12, 45, 69, 22])

indices_booleanos = [False, False, True, False, False, True]

arr_filter = arr[indices_booleanos]

print(f"Array original: {arr}")
print(f"indices booleanos: {indices_booleanos}")
print(f"Array filtrado: {arr_filter}")

Array original: [37 85 12 45 69 22]
indices booleanos: [False, False, True, False, False, True]
Array filtrado: [12 22]


As you can see, the filtered array (`arr_filetr`), has only been left from the original array (`arr`) with the elements that match those where the array `indices_booleans` is `True`.

Another thing we can see is that it has only kept the even elements, so now we will see how to keep the even elements of an array, without having to do it by hand as we have done in the previous example

In [ ]:
arr = np.array([[1, 2, 3, 4, 5], 
                [6, 7, 8, 9, 10]])
 
indices_booleanos = arr % 2 == 0
 
arr_filter = arr[indices_booleanos]
 
print(f"Array original: {arr}\n")
print(f"indices booleanos: {indices_booleanos}\n")
print(f"Array filtrado: {arr_filter}")

Array original: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

indices booleanos: [[False  True False  True False]
 [ True False  True False  True]]

Array filtrado: [ 2  4  6  8 10]
