# Cálculo Matrix com Numpy

## 1. Resumen

Este caderno foi traduzido automaticamente para torná-lo acessível a mais pessoas, por favor me avise se você vir algum erro de digitação..

Vamos ver uma pequena introdução à biblioteca de cálculo da matriz 'Numpy'. Esta biblioteca foi projetada para todos os tipos de cálculo matricial, portanto, vamos ficar apenas com a parte que será útil para entender os cálculos dentro das redes neurais, mas deixaremos de fora coisas interessantes como o uso da biblioteca para álgebra linear.


<p align="center">
  <img src="https://github.com/DeepMaxFN/DeepMaxFN-blog/blob/master/images/numpy-icon.png?raw=true">
</p>

## O que é Numpy?

Numpy é uma biblioteca Python projetada para fazer o cálculo matricial. A computação matricial é algo muito utilizado na ciência em geral e na ciência dos dados em particular, portanto é necessário ter uma biblioteca que faça isso muito bem.

Seu nome significa píton numérico

Seu objetivo principal é o "ndarray", que encapsula "n" matrizes dimensionais de tipos de dados homogêneos, ao contrário das listas Python que podem ter dados de diferentes tipos.

O Numpy pretende realizar o cálculo matricial muito mais rápido que as listas Python, mas como isso é possível?

* O Numpy usa código compilado, enquanto o Python usa código interpretado. A diferença é que Python em tempo de execução tem que interpretar, compilar e executar o código, enquanto em Numpy ele já está compilado, então ele roda mais rápido.
* Os `ndarray`s têm um tamanho fixo, ao contrário das listas Python que são dinâmicas. Se em Numpy você quiser mudar o tamanho de uma matriz, uma nova será criada e a antiga será excluída.
* Todos os elementos dos `ndarray`s são do mesmo tipo de dados, ao contrário das listas Python que podem ter elementos de tipos diferentes.
* Parte do código numérico está escrito em C/C++ (muito mais rápido que Python).
* Os dados da matriz são armazenados na memória continuamente, ao contrário das listas de Python, o que torna a manipulação muito mais rápida.

Numpy oferece a facilidade de usar código que é simples de escrever e ler, mas que é escrito e pré-compilado em C, tornando-o muito mais rápido.
 
Suponha que queremos multiplicar dois vetores, isso seria feito em C da seguinte forma
 
```c
para (i = 0; i < filas; i++): {
  para (j = 0; j < colunas; j++): {
    c[i][j] = a[i][j]*b[i][j];
  }
}
```
 
Numpy oferece a possibilidade de executar este código por baixo, mas muito mais fácil de escrever e entender por meio de
 
``píton
c = a * b
```

O Numpy oferece código vetorizado, o que significa que você não precisa escrever loops, mas eles estão, no entanto, sendo executados por baixo em código C otimizado e pré-compilado. Isto tem as seguintes vantagens:

* O código é mais fácil de escrever e ler.
* Menos linhas de código significa que é provável que menos erros sejam introduzidos.
* O código parece mais uma notação matemática.

### 2.1. Numpy como `np`.

Geralmente, ao importar o Numpy, ele é importado com o pseudônimo `np`.

In [1]:
import numpy as np

print(np.__version__)

1.18.1


## 3. Velocidade numérica

Como explicado acima, Numpy executa o cálculo muito mais rápido do que as listas Python, vejamos um exemplo em que o produto escalar de duas matrizes é executado, utilizando listas Python e `ndarray`s.

In [2]:
from time import time
 
# Dimensión de las matrices
dim = 1000
shape = (dim, dim)
 
# Se crean dos ndarrays de Numpy de dimensión dim x dim
ndarray_a = np.ones(shape=shape)
ndarray_b = np.ones(shape=shape)
 
# Se crean dos listas de Python de dimensión dim x dim a partir de los ndarrays
list_a = list(ndarray_a)
list_b = list(ndarray_b)
 
# Se crean el ndarray y la lista de Python donde se guardarán los resultados
ndarray_c = np.empty(shape=shape)
list_c = list(ndarray_c)
 
# Producto escalar de dos listas de python
t0 = time()
for fila in range(dim):
  for columna in range(dim):
    list_c[fila][columna] = list_a[fila][columna] * list_b[fila][columna]
t = time()
t_listas = t-t0
print(f"Tiempo para realizar el producto escalar de dos listas de Python de dimensiones {dim}x{dim}: {t_listas:.4f} ms")
 
 
# Producto escalar de dos ndarrays de Numpy
t0 = time()
ndarray_c = ndarray_a * ndarray_b
t = time()
t_ndarrays = t-t0
print(f"Tiempo para realizar el producto escalar de dos ndarrays de Numpy de dimensiones {dim}x{dim}: {t_ndarrays:.4f} ms")
 
# Comparación de tiempos
print(f"\nHacer el cálculo con listas de Python tarda {t_listas/t_ndarrays:.2f} veces más rápido que con ndarrays de Numpy")

Tiempo para realizar el producto escalar de dos listas de Python de dimensiones 1000x1000: 0.5234 ms
Tiempo para realizar el producto escalar de dos ndarrays de Numpy de dimensiones 1000x1000: 0.0017 ms

Hacer el cálculo con listas de Python tarda 316.66 veces más rápido que con ndarrays de Numpy


## 4. arrays em Numpy

Em Numpy, uma matriz é um objeto de "raiva".

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


### 4.1. Como criar matrizes

Com o método `array()` você pode criar `ndarray`s inserindo listas Python (como no exemplo acima), ou tuples.

In [ ]:
arr = np.array((1, 2, 3, 4, 5))

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


O método `zeros()` pode ser utilizado para criar matrizes preenchidas com zeros.

In [3]:
arr = np.zeros((3, 4))

print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


O método `zeros_like(A)` devolve uma matriz com a mesma forma que a matriz A, mas cheia de zeros.

In [ ]:
A = np.array((1, 2, 3, 4, 5))
arr = np.zeros_like(A)

print(arr)

[0 0 0 0 0]


O método `ones()` pode ser utilizado para criar matrizes preenchidas com

In [ ]:
arr = np.ones((4, 3))

print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


O método `ones_like(A)` devolve uma matriz com a mesma forma que a matriz A, mas cheia de zeros.

In [ ]:
A = np.array((1, 2, 3, 4, 5))
arr = np.ones_like(A)

print(arr)

[1 1 1 1 1]


Com o método `empty()`, você pode criar matrizes com as dimensões que quiser, mas inicializadas aleatoriamente.

In [ ]:
arr = np.empty((6, 3))

print(arr)

[[4.66169180e-310 2.35541533e-312 2.41907520e-312]
 [2.14321575e-312 2.46151512e-312 2.31297541e-312]
 [2.35541533e-312 2.05833592e-312 2.22809558e-312]
 [2.56761491e-312 2.48273508e-312 2.05833592e-312]
 [2.05833592e-312 2.29175545e-312 2.07955588e-312]
 [2.14321575e-312 0.00000000e+000 0.00000000e+000]]


O método `empty_like(A)` devolve uma matriz com a mesma forma que a matriz A, mas inicializada aleatoriamente.

In [ ]:
A = np.array((1, 2, 3, 4, 5))
arr = np.empty_like(A)

print(arr)

[4607182418800017408 4611686018427387904 4613937818241073152
 4616189618054758400 4617315517961601024]


Com o método `arange(start, stop, step)` você pode criar matrizes em uma determinada faixa. Este método é similar ao método "Python's `range()` do Python.

In [ ]:
arr = np.arange(10, 30, 5)

print(arr)

[10 15 20 25]


Quando se utiliza `arange` com argumentos de ponto flutuante, geralmente não é possível prever o número de elementos obtidos, pois a precisão do ponto flutuante é finita.

Por esta razão, muitas vezes é melhor utilizar a função "espaço-linha(start, stop, n)`, que toma como argumento o número de elementos que queremos, ao invés do "espaço-linha(start, stop, n)`passo".

In [ ]:
arr = np.linspace(0, 2, 9)
 
print(arr)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


### 4.2. Dimensões da matriz

Na Numpy, podemos criar matrizes de qualquer dimensão. Para obter a dimensão de uma matriz, utilizamos o método "endim".

Matriz de dimensão 0, que seria equivalente a um número

In [ ]:
arr = np.array(42)

print(arr)
print(arr.ndim)

42
0


Matriz de dimensão 1, que seria equivalente a um vetor

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(arr.ndim)

[1 2 3 4 5]
1


Matriz de dimensão 2, que seria equivalente a uma matriz

In [ ]:
arr = np.array([[1, 2, 3, 4, 5], 
                [6, 7, 8, 9, 10]])

print(arr)
print(arr.ndim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2


Matriz da dimensão 3

In [ ]:
arr = np.array([
                [[1, 2, 3, 4, 5], 
                [6, 7, 8, 9, 10]],
                
                [[11, 12, 13, 14, 15], 
                [16, 17, 18, 19, 20]]
                ])

print(arr)
print(arr.ndim)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
3


Ao criar 'ndarray`s, o número de dimensões pode ser definido utilizando o parâmetro 'ndim'.

In [ ]:
arr = np.array([1, 2, 3, 4, 5], ndmin=6)

print(arr)
print(arr.ndim)

[[[[[[1 2 3 4 5]]]]]]
6


## 5. tipo de dados

Os dados que a Numpy arrays pode armazenar são os seguintes:


*`i` - Entero
* 'b' - Booleano
*`u` - Número inteiro não assinado
* `f` - Flotante
* c'' - Complexo flutuante
*`m` - Timedelta
* `M` - Data/hora
* `O` - Objeto
*`S` - Cordão
* `U` - Cadeia Unicode
* V' - Fragmento de memória fixo para outro tipo (vazio)

Podemos verificar o tipo de dados de uma matriz utilizando o `dtype`.

In [ ]:
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

int64
<U6


Também podemos criar arrays indicando o tipo de dados que queremos que tenha utilizando o `dtype`.

In [ ]:
arr = np.array([1, 2, 3, 4], dtype='i')
print("Enteros:")
print(arr)
print(arr.dtype)
 
arr = np.array([1, 2, 3, 4], dtype='f')
print("\nFloat:")
print(arr)
print(arr.dtype)
 
arr = np.array([1, 2, 3, 4], dtype='f')
print("\nComplejos:")
print(arr)
print(arr.dtype)
 
arr = np.array([1, 2, 3, 4], dtype='S')
print("\nString:")
print(arr)
print(arr.dtype)
 
arr = np.array([1, 2, 3, 4], dtype='U')
print("\nUnicode string:")
print(arr)
print(arr.dtype)
 
arr = np.array([1, 2, 3, 4], dtype='O')
print("\nObjeto:")
print(arr)
print(arr.dtype)

Enteros:
[1 2 3 4]
int32

Float:
[1. 2. 3. 4.]
float32

Complejos:
[1. 2. 3. 4.]
float32

String:
[b'1' b'2' b'3' b'4']
|S1

Unicode string:
['1' '2' '3' '4']
<U1

Objeto:
[1 2 3 4]
object


## 6. operações matemáticas

### 6.1. Operações básicas

As operações com matrizes são realizadas por elementos, por exemplo, se adicionarmos duas matrizes, os elementos de cada matriz da mesma posição serão adicionados, como é feito na soma matemática de duas matrizes.

In [ ]:
A = np.array([1, 2, 3])
B = np.array([1, 2, 3])

print(f"Matriz A: tamaño {A.shape}\n{A}\n")
print(f"Matriz B: tamaño {B.shape}\n{B}\n")

C = A + B
print(f"Matriz C: tamaño {C.shape}\n{C}\n")

D = A - B
print(f"Matriz D: tamaño {D.shape}\n{D}")

Matriz A: tamaño (3,)
[1 2 3]

Matriz B: tamaño (3,)
[1 2 3]

Matriz C: tamaño (3,)
[2 4 6]

Matriz D: tamaño (3,)
[0 0 0]


Entretanto, se multiplicarmos duas matrizes, também multiplicamos cada elemento das matrizes (produto escalar).

In [ ]:
A = np.array([[3, 5], [4, 1]])
B = np.array([[1, 2], [-3, 0]])
 
print(f"Matriz A: tamaño {A.shape}\n{A}\n")
print(f"Matriz B: tamaño {B.shape}\n{B}\n")
 
C = A * B
print(f"Matriz C: tamaño {C.shape}\n{C}\n")

Matriz A: tamaño (2, 2)
[[3 5]
 [4 1]]

Matriz B: tamaño (2, 2)
[[ 1  2]
 [-3  0]]

Matriz C: tamaño (2, 2)
[[  3  10]
 [-12   0]]



Para fazer o produto matricial que foi ensinado em matemática durante toda a sua vida você tem que utilizar o método `@` operador ou o método `dot`.

In [ ]:
A = np.array([[3, 5], [4, 1], [6, -1]])
B = np.array([[1, 2, 3], [-3, 0, 4]])

print(f"Matriz A: tamaño {A.shape}\n{A}\n")
print(f"Matriz B: tamaño {B.shape}\n{B}\n")

C = A @ B
print(f"Matriz C: tamaño {C.shape}\n{C}\n")

D = A.dot(B)
print(f"Matriz D: tamaño {D.shape}\n{D}")

Matriz A: tamaño (3, 2)
[[ 3  5]
 [ 4  1]
 [ 6 -1]]

Matriz B: tamaño (2, 3)
[[ 1  2  3]
 [-3  0  4]]

Matriz C: tamaño (3, 3)
[[-12   6  29]
 [  1   8  16]
 [  9  12  14]]

Matriz D: tamaño (3, 3)
[[-12   6  29]
 [  1   8  16]
 [  9  12  14]]


Se ao invés de criar uma nova matriz, você quiser modificar uma matriz existente, você pode utilizar os botões `+=`, `-=` ou `*=`.

In [ ]:
A = np.array([[3, 5], [4, 1]])
B = np.array([[1, 2], [-3, 0]])

print(f"Matriz A: tamaño {A.shape}\n{A}\n")
print(f"Matriz B: tamaño {B.shape}\n{B}\n")

A += B
print(f"Matriz A tras suma: tamaño {A.shape}\n{A}\n")

A -= B
print(f"Matriz A tras resta: tamaño {A.shape}\n{A}\n")

A *= B
print(f"Matriz A tras multiplicación: tamaño {A.shape}\n{A}\n")

Matriz A: tamaño (2, 2)
[[3 5]
 [4 1]]

Matriz B: tamaño (2, 2)
[[ 1  2]
 [-3  0]]

Matriz A tras suma: tamaño (2, 2)
[[4 7]
 [1 1]]

Matriz A tras resta: tamaño (2, 2)
[[3 5]
 [4 1]]

Matriz A tras multiplicación: tamaño (2, 2)
[[  3  10]
 [-12   0]]



As operações podem ser realizadas em todos os elementos de uma matriz, isto é, graças a uma propriedade chamada "brodcasting", sobre a qual veremos mais adiante.

In [ ]:
A = np.array([[3, 5], [4, 1]])
 
print(f"Matriz A: tamaño {A.shape}\n{A}\n")
 
B = A * 2
print(f"Matriz B: tamaño {B.shape}\n{B}\n")
 
C = A ** 2
print(f"Matriz C: tamaño {C.shape}\n{C}\n")
 
D = 2*np.sin(A)
print(f"Matriz D: tamaño {D.shape}\n{D}")

Matriz A: tamaño (2, 2)
[[3 5]
 [4 1]]

Matriz B: tamaño (2, 2)
[[ 6 10]
 [ 8  2]]

Matriz C: tamaño (2, 2)
[[ 9 25]
 [16  1]]

Matriz D: tamaño (2, 2)
[[ 0.28224002 -1.91784855]
 [-1.51360499  1.68294197]]


### 6.2. Funções nas matrizes

Como você pode ver no último cálculo, a Numpy oferece operadores de funções em matrizes, existem muitas [funções] (https://numpy.org/doc/stable/reference/routines.html) que podem ser realizadas em matrizes, álgebra matemática, lógica, linear, etc. Aqui estão alguns deles

In [ ]:
A = np.array([[3, 5], [4, 1]])

print(f"A\n{A}\n")

print(f"exp(A)\n{np.exp(A)}\n")
print(f"sqrt(A)\n{np.sqrt(A)}\n")
print(f"cos(A)\n{np.cos(A)}\n")

A
[[3 5]
 [4 1]]

exp(A)
[[ 20.08553692 148.4131591 ]
 [ 54.59815003   2.71828183]]

sqrt(A)
[[1.73205081 2.23606798]
 [2.         1.        ]]

cos(A)
[[-0.9899925   0.28366219]
 [-0.65364362  0.54030231]]



Há algumas funções que retornam informações das matrizes, tais como a média

In [ ]:
A = np.array([[3, 5], [4, 1]])

print(f"A\n{A}\n")

print(f"A.mean()\n{A.mean()}\n")

A
[[3 5]
 [4 1]]

A.mean()
3.25



Entretanto, podemos obter estas informações para cada eixo por meio do atributo "eixo", se este for 0 é feito em cada coluna, enquanto que se for 1 é feito em cada linha.

In [ ]:
A = np.array([[3, 5], [4, 1]])
 
print(f"A\n{A}\n")
 
print(f"A.mean() columnas\n{A.mean(axis=0)}\n")
print(f"A.mean() filas\n{A.mean(axis=1)}\n")

A
[[3 5]
 [4 1]]

A.mean() columnas
[3.5 3. ]

A.mean() filas
[4.  2.5]



### 6.3. Broadcasting

Podem ser realizadas operações com matrizes, com matrizes de diferentes dimensões. Neste caso, o Numpy detectará isto e fará uma projeção da matriz menor até igualar a maior.

![numpy_broadcasting](https://raw.githubusercontent.com/DeepMaxFN/DeepMaxFN-blog/master/images/numpy_broadcasting.png)

Esta é uma grande característica do Numpy, que torna possível realizar cálculos em matrizes sem ter que se preocupar em combinar as dimensões das matrizes.

In [ ]:
A = np.array([1, 2, 3])

print(f"A\n{A}\n")

B = A + 5

print(f"B\n{B}\n")

A
[1 2 3]

B
[6 7 8]



In [ ]:
A = np.array([1, 2, 3])
B = np.ones((3,3))

print(f"A\n{A}\n")
print(f"B\n{B}\n")

C = A + B

print(f"C\n{C}\n")

A
[1 2 3]

B
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

C
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]



In [ ]:
A = np.array([1, 2, 3])
B = np.array([[1], [2], [3]])
 
print(f"A\n{A}\n")
print(f"B\n{B}\n")
 
C = A + B
 
print(f"C\n{C}\n")

A
[1 2 3]

B
[[1]
 [2]
 [3]]

C
[[2 3 4]
 [3 4 5]
 [4 5 6]]



## 7. indexação matricial

A indexação de matrizes é feita da mesma forma que com as listas Python.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr[3]

4

No caso de mais de uma dimensão, o índice deve ser indicado em cada uma delas.

In [ ]:
arr = np.array([[1, 2, 3, 4, 5], 
                [6, 7, 8, 9, 10]])
arr[1, 2]

8

A indexação negativa pode ser usada

In [ ]:
arr[-1, -2]

9

Se você não indicar um dos eixos, considera-se que você quer o eixo inteiro.

In [ ]:
arr = np.array([[1, 2, 3, 4, 5], 
                [6, 7, 8, 9, 10]])
arr[1]

array([ 6,  7,  8,  9, 10])

### 7.1. Porções de matrizes

Ao indexar podemos manter partes de arrays como fizemos com as listas Python.

Lembre-se que isso foi feito da seguinte maneira:

`start:stop:step`

Onde o intervalo vai de "início" (incluído) a "parada" (não incluído) com um passo de "passo".

Se o "passo" não for especificado, o padrão é 1

Por exemplo, se quisermos itens da segunda fila e da segunda à quarta coluna:

* Selecione a segunda fila com um 1 (já que começa a contar a partir de 0).
* Selecionamos da segunda para a quarta linha usando 1:4, o 1 para indicar a segunda coluna e o 4 para indicar a quinta (já que o segundo número indica a coluna em que termina sem incluir esta coluna). Os dois números levando em conta que começamos a contar a partir de 0.

In [ ]:
print(arr)
print(arr[1, 1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[7 8 9]


Podemos tomar de uma posição até o fim

In [ ]:
arr[1, 2:]

array([ 8,  9, 10])

Desde o início até uma posição

In [ ]:
arr[1, :3]

array([6, 7, 8])

Definir a faixa com números negativos

In [ ]:
arr[1, -3:-1]

array([8, 9])

Escolhendo a etapa

In [ ]:
arr[1, 1:4:2]

array([7, 9])

### 7.2. Iteração em matrizes

A iteração em matrizes multidimensionais é feita em relação ao primeiro eixo

In [ ]:
M = np.array( [[[  0,  1,  2],
                [ 10, 12, 13]],
               [[100,101,102],
                [110,112,113]]])

print(f'Matriz de dimensión: {M.shape}\n')

i = 0
for fila in M:
  print(f'Fila {i}: {fila}')
  i += 1

Matriz de dimensión: (2, 2, 3)

Fila 0: [[ 0  1  2]
 [10 12 13]]
Fila 1: [[100 101 102]
 [110 112 113]]


Entretanto, se quisermos iterar através de cada item, podemos usar o método 'plano'.

In [ ]:
i = 0
for fila in M.flat:
  print(f'Elemento {i}: {fila}')
  i += 1

Elemento 0: 0
Elemento 1: 1
Elemento 2: 2
Elemento 3: 10
Elemento 4: 12
Elemento 5: 13
Elemento 6: 100
Elemento 7: 101
Elemento 8: 102
Elemento 9: 110
Elemento 10: 112
Elemento 11: 113


## 8. matrizes de cópia

Na Numpy temos duas formas de copiar matrizes, por "cópia", que faz uma nova cópia da matriz, e por "visão", que faz uma visão da matriz original.
 
A cópia possui os dados e quaisquer alterações feitas na cópia não afetarão a matriz original, e quaisquer alterações feitas na matriz original não afetarão a cópia.
 
A visão não possui os dados e qualquer alteração feita na cópia afetará a matriz original, e qualquer alteração feita na matriz original afetará a cópia.

### 8.1. Cópia

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
copy_arr = arr.copy()
arr[0] = 42
copy_arr[1] = 43
 
print(f'Original: {arr}')
print(f'Copia:    {copy_arr}')

Original: [42  2  3  4  5]
Copia:    [ 1 43  3  4  5]


### 8.2. Ver

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
view_arr = arr.view()
arr[0] = 42
view_arr[1] = 43
 
print(f'Original: {arr}')
print(f'Vista:    {view_arr}')

Original: [42 43  3  4  5]
Vista:    [42 43  3  4  5]


### 8.3. Titular dos dados

Em caso de dúvida sobre se temos uma cópia ou uma visão, podemos utilizar o `base`.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
 
copy_arr = arr.copy()
view_arr = arr.view()
 
print(copy_arr.base)
print(view_arr.base)

None
[1 2 3 4 5]


## 9. forma de matrizes

Podemos conhecer a forma da matriz utilizando o método `shape'. Isto retornará um tuple, o tamanho do tuple representa as dimensões da matriz, cada elemento do tuple indica o número de itens em cada uma das dimensões da matriz.

In [ ]:
arr = np.array([
                [[1, 2, 3, 4, 5], 
                [6, 7, 8, 9, 10]],
                
                [[11, 12, 13, 14, 15], 
                [16, 17, 18, 19, 20]]
                ])
 
print(arr)
print(arr.shape)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
(2, 2, 5)


### 9.1. Reformular

Podemos mudar a forma das matrizes para o que quisermos, utilizando o método "reformar".

Por exemplo, a matriz acima, que tem uma forma de `(2, 2, 4)`. Podemos passá-lo para `(5, 4)`.

In [ ]:
arr_reshape = arr.reshape(5, 4)

print(arr_reshape)
print(arr_reshape.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
(5, 4)


Observe que, para redimensionar as matrizes, o número de itens no novo formulário deve ter o mesmo número de itens que no primeiro formulário.

Ou seja, no exemplo acima, a primeira matriz tinha 20 itens (2x2x4), e a nova matriz tem 20 itens (5x4). O que não podemos fazer é redimensioná-lo para uma variedade de tamanhos (3, 4), pois haveria 12 itens no total.

In [ ]:
arr_reshape = arr.reshape(3, 4)

ValueError: ignored

### 9.2. Dimensão desconhecida

Caso queiramos mudar a forma de uma matriz e não nos importamos com uma das dimensões, ou não a conhecemos, podemos fazer com que o Numpy a calcule para nós, inserindo um `-1` como parâmetro.

In [ ]:
arr = np.array([
                [[1, 2, 3, 4, 5], 
                [6, 7, 8, 9, 10]],
                
                [[11, 12, 13, 14, 15], 
                [16, 17, 18, 19, 20]]
                ])

arr_reshape = arr.reshape(2, -1)

print(arr_reshape)
print(arr_reshape.shape)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
(2, 10)


Note que não se pode colocar um número qualquer nas dimensões conhecidas. O número de itens na matriz original tem que ser um múltiplo das dimensões conhecidas.

No exemplo acima, a matriz tem 20 itens, que é um múltiplo de 2, a dimensão conhecida entrada. Um 3 não poderia ter sido inserido como a dimensão conhecida, já que 20 não é um múltiplo de 3, e não haveria um número que pudesse ser inserido na dimensão desconhecida que faria um total de 20 itens.

### 9.3. Aplainamento de matrizes

Podemos achatar matrizes, ou seja, torná-las unidimensionais por `reshape(-1)`. Desta forma, quaisquer que sejam as dimensões da matriz original, a nova matriz terá sempre apenas uma dimensão.

In [ ]:
arr = np.array([
                [[1, 2, 3, 4, 5], 
                [6, 7, 8, 9, 10]],
                
                [[11, 12, 13, 14, 15], 
                [16, 17, 18, 19, 20]]
                ])

arr_flatten = arr.reshape(-1)

print(arr_flatten)
print(arr_flatten.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
(20,)


Outra maneira de aplanar uma matriz é utilizando o método `ravel()`.

In [ ]:
arr = np.array([
                [[1, 2, 3, 4, 5], 
                [6, 7, 8, 9, 10]],
                
                [[11, 12, 13, 14, 15], 
                [16, 17, 18, 19, 20]]
                ])

arr_flatten = arr.ravel()

print(arr_flatten)
print(arr_flatten.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
(20,)


### 9.4. Matriz transposta

A transposição de uma matriz pode ser obtida utilizando o método `T'. Para fazer a transposição de uma matriz é trocar as linhas e colunas da matriz, a imagem a seguir mostra um exemplo que a torna mais clara

![transpose_matrix](https://github.com/DeepMaxFN/DeepMaxFN-blog/blob/master/images/Transpose_matrix.png?raw=true)

In [ ]:
arr = np.array([[1, 0, 4], 
                [0, 5, 0],
                [6, 0, -9]])
 
arr_t = arr.T
 
print(arr_t)
print(arr_t.shape)

[[ 1  0  6]
 [ 0  5  0]
 [ 4  0 -9]]
(3, 3)


## 10. Empilhamento matricial

### 10.1 Empilhamento vertical

Os matricecs podem ser empilhados verticalmente (unindo linhas) utilizando o método `vstack()`.

In [ ]:
a = np.array([[1, 1, 1], 
              [2, 2, 2],
              [3, 3, 3]])

b = np.array([[4, 4, 4], 
              [5, 5, 5],
              [6, 6, 6]])

c = np.vstack((a,b))
c

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4],
       [5, 5, 5],
       [6, 6, 6]])

Se você tiver matrizes de mais de 2 dimensões, `vsatck()` empilhará ao longo da primeira dimensão.

In [ ]:
a = np.array([
                [[1, 1], 
                [2, 2]],
                
                [[3, 3], 
                [4, 4]]
                ])
 
b = np.array([
                [[5, 5], 
                [6, 6]],
                
                [[7, 7], 
                [8, 8]]
                ])
 
c = np.vstack((a,b))
c

array([[[1, 1],
        [2, 2]],

       [[3, 3],
        [4, 4]],

       [[5, 5],
        [6, 6]],

       [[7, 7],
        [8, 8]]])

### 10.2 Empilhamento horizontal

Você pode empilhar arrays horizontalmente (unindo colunas) utilizando o método `hstack()`.

In [ ]:
a = np.array([[1, 2, 3], 
              [1, 2, 3],
              [1, 2, 3]])

b = np.array([[4, 5, 6], 
              [4, 5, 6],
              [4, 5, 6]])

c = np.hstack((a,b))
c

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

Se você tiver matrizes de mais de 2 dimensões `hsatck()` empilhará ao longo da segunda dimensão.

In [ ]:
a = np.array([
                [[1, 1], 
                [2, 2]],
                
                [[3, 3], 
                [4, 4]]
                ])

b = np.array([
                [[5, 5], 
                [6, 6]],
                
                [[7, 7], 
                [8, 8]]
                ])

c = np.hstack((a,b))
c

array([[[1, 1],
        [2, 2],
        [5, 5],
        [6, 6]],

       [[3, 3],
        [4, 4],
        [7, 7],
        [8, 8]]])

Outra maneira de adicionar colunas a uma matriz é utilizando o método `column_stack()`.

In [ ]:
a = np.array([[1, 2, 3], 
              [1, 2, 3],
              [1, 2, 3]])
 
b = np.array([4, 4, 4])
 
c = np.column_stack((a,b))
c

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

### 10.3. empilhamento profundo

Você pode empilhar arrays em profundidade (terceira dimensão) utilizando o método `dstack()`.

In [ ]:
a = np.array([
                [[1, 1], 
                [2, 2]],
                
                [[3, 3], 
                [4, 4]]
                ])

b = np.array([
                [[1, 1], 
                [2, 2]],
                
                [[3, 3], 
                [4, 4]]
                ])

c = np.dstack((a,b))
print(f"c: {c}\n")
print(f"a.shape: {a.shape}, b.shape: {b.shape}, c.shape: {c.shape}")

c: [[[1 1 1 1]
  [2 2 2 2]]

 [[3 3 3 3]
  [4 4 4 4]]]

a.shape: (2, 2, 2), b.shape: (2, 2, 2), c.shape: (2, 2, 4)


Se você tiver matrizes de mais de 4 dimensões `dsatck()` empilhará ao longo da terceira dimensão.

In [ ]:
a = np.array([1, 2, 3, 4, 5], ndmin=4)

b = np.array([1, 2, 3, 4, 5], ndmin=4)

c = np.dstack((a,b))
print(f"a.shape: {a.shape}, b.shape: {b.shape}, c.shape: {c.shape}")

a.shape: (1, 1, 1, 5), b.shape: (1, 1, 1, 5), c.shape: (1, 1, 2, 5)


### 10.3. empilhamento personalizado

Utilizando o método `concatenate()`, você pode escolher o eixo no qual você quer empilhar as matrizes.

In [ ]:
a = np.array([
                [[1, 1], 
                [2, 2]],
                
                [[3, 3], 
                [4, 4]]
                ])

b = np.array([
                [[5, 5], 
                [6, 6]],
                
                [[7, 7], 
                [8, 8]]
                ])

conc0 = np.concatenate((a,b), axis=0) # concatenamiento en el primer eje
conc1 = np.concatenate((a,b), axis=1) # concatenamiento en el segundo eje
conc2 = np.concatenate((a,b), axis=2) # concatenamiento en el tercer eje
print(f"conc0: {conc0}\n")
print(f"conc1: {conc1}\n")
print(f"conc2: {conc2}")

conc0: [[[1 1]
  [2 2]]

 [[3 3]
  [4 4]]

 [[5 5]
  [6 6]]

 [[7 7]
  [8 8]]]

conc1: [[[1 1]
  [2 2]
  [5 5]
  [6 6]]

 [[3 3]
  [4 4]
  [7 7]
  [8 8]]]

conc2: [[[1 1 5 5]
  [2 2 6 6]]

 [[3 3 7 7]
  [4 4 8 8]]]


## 11. matrizes divisórias

### 11.1 Dividir verticalmente

Você pode dividir os matricecs verticalmente (separando linhas) utilizando o método `vsplit()`.

In [ ]:
a = np.array([[1.1, 1.2, 1.3, 1.4], 
              [2.1, 2.2, 2.3, 2.4],
              [3.1, 3.2, 3.3, 3.4],
              [4.1, 4.2, 4.3, 4.4]])

[a1, a2] = np.vsplit(a, 2)
print(f"a1: {a1}\n")
print(f"a2: {a2}")

a1: [[1.1 1.2 1.3 1.4]
 [2.1 2.2 2.3 2.4]]

a2: [[3.1 3.2 3.3 3.4]
 [4.1 4.2 4.3 4.4]]


Se você tiver matrizes de mais de 2 dimensões `vsplit()`dividir-se-á ao longo da primeira dimensão.

In [ ]:
a = np.array([
                [[1, 1], 
                [2, 2]],
                
                [[3, 3], 
                [4, 4]]
                ])

[a1, a2] = np.vsplit(a, 2)
print(f"a1: {a1}\n")
print(f"a2: {a2}")

a1: [[[1 1]
  [2 2]]]

a2: [[[3 3]
  [4 4]]]


### 11.2 Dividir horizontalmente

Você pode dividir as matrizes horizontalmente (separando as colunas) utilizando o método `hsplit()`.

In [ ]:
a = np.array([[1.1, 1.2, 1.3, 1.4], 
              [2.1, 2.2, 2.3, 2.4],
              [3.1, 3.2, 3.3, 3.4],
              [4.1, 4.2, 4.3, 4.4]])

[a1, a2] = np.hsplit(a, 2)
print(f"a1: {a1}\n")
print(f"a2: {a2}")

a1: [[1.1 1.2]
 [2.1 2.2]
 [3.1 3.2]
 [4.1 4.2]]

a2: [[1.3 1.4]
 [2.3 2.4]
 [3.3 3.4]
 [4.3 4.4]]


Se você tiver matrizes de mais de duas dimensões, "divididas" se dividirão ao longo da segunda dimensão.

In [ ]:
a = np.array([
                [[1, 1], 
                [2, 2]],
                
                [[3, 3], 
                [4, 4]]
                ])

[a1, a2] = np.hsplit(a, 2)
print(f"a1: {a1}\n")
print(f"a2: {a2}")

a1: [[[1 1]]

 [[3 3]]]

a2: [[[2 2]]

 [[4 4]]]


### 11.3 Fenda personalizada

Utilizando o método `array_split()`, você pode escolher o eixo no qual você quer dividir as matrizes.

In [ ]:
a = np.array([
                [[1, 1], 
                [2, 2]],
                
                [[3, 3], 
                [4, 4]]
                ])

[a1_eje0, a2_eje0] = np.array_split(a, 2, axis=0)
[a1_eje1, a2_eje1] = np.array_split(a, 2, axis=1)
[a1_eje2, a2_eje2] = np.array_split(a, 2, axis=2)

print(f"a1_eje0: {a1_eje0}\n")
print(f"a2_eje0: {a2_eje0}\n\n")

print(f"a1_eje1: {a1_eje1}\n")
print(f"a2_eje1: {a2_eje1}\n\n")

print(f"a1_eje2: {a1_eje2}\n")
print(f"a2_eje2: {a2_eje2}")

a1_eje0: [[[1 1]
  [2 2]]]

a2_eje0: [[[3 3]
  [4 4]]]


a1_eje1: [[[1 1]]

 [[3 3]]]

a2_eje1: [[[2 2]]

 [[4 4]]]


a1_eje2: [[[1]
  [2]]

 [[3]
  [4]]]

a2_eje2: [[[1]
  [2]]

 [[3]
  [4]]]


## 12. pesquisa em matrizes

Se você quiser procurar por um valor dentro de uma matriz, você pode utilizar o método `onde()` que retorna as posições onde a matriz vale o valor que você está procurando.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

ids = np.where(arr == 4)
ids

(array([3, 5, 6]),)

Você pode usar funções para pesquisar, por exemplo, se você quiser pesquisar em que posições os valores são pares

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

ids = np.where(arr%2)
ids

(array([0, 2, 4, 6]),)

## 13. matrizes de pedidos

Utilizando o método `sort()` podemos ordenar arrays

In [ ]:
arr = np.array([3, 2, 0, 1])

arr_ordenado = np.sort(arr)
arr_ordenado

array([0, 1, 2, 3])

Se o que temos são cordas, elas são ordenadas alfabeticamente.

In [ ]:
arr = np.array(['banana', 'apple', 'cherry'])

arr_ordenado = np.sort(arr)
arr_ordenado

array(['apple', 'banana', 'cherry'], dtype='<U6')

E as matrizes booleanas também são encomendadas por

In [ ]:
arr = np.array([True, False, True])

arr_ordenado = np.sort(arr)
arr_ordenado

array([False,  True,  True])

Se você tiver matrizes de mais de uma dimensão, ele as ordena por dimensões, ou seja, se você tiver uma matriz bidimensional, ele ordena os números da primeira linha entre elas e os números da segunda linha entre elas.

In [ ]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

arr_ordenado = np.sort(arr)
arr_ordenado

array([[2, 3, 4],
       [0, 1, 5]])

Por padrão, ele sempre ordena com relação às linhas, mas se você quiser que ele ordene com relação a outra dimensão, você tem que especificá-lo com a variável "eixo".

In [ ]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

arr_ordenado0 = np.sort(arr, axis=0) # Se ordena con respecto a la primera dimensión
arr_ordenado1 = np.sort(arr, axis=1) # Se ordena con respecto a la segunda dimensión

print(f"arr_ordenado0: {arr_ordenado0}\n")
print(f"arr_ordenado1: {arr_ordenado1}\n")

arr_ordenado0: [[3 0 1]
 [5 2 4]]

arr_ordenado1: [[2 3 4]
 [0 1 5]]



## 14 Filtros em matrizes

Numpy oferece a possibilidade de procurar certos elementos de uma matriz e criar uma nova.

Ele faz isso criando uma matriz de índices booleanos, ou seja, ele cria uma nova matriz que indica quais posições da matriz estamos mantendo e quais não estamos mantendo.

Vejamos um exemplo de uma matriz de índices booleanos

In [ ]:
arr = np.array([37, 85, 12, 45, 69, 22])

indices_booleanos = [False, False, True, False, False, True]

arr_filter = arr[indices_booleanos]

print(f"Array original: {arr}")
print(f"indices booleanos: {indices_booleanos}")
print(f"Array filtrado: {arr_filter}")

Array original: [37 85 12 45 69 22]
indices booleanos: [False, False, True, False, False, True]
Array filtrado: [12 22]


Como você pode ver, a matriz filtrada (`arr_filetr`), só foi deixada da matriz original (`arr`) com os elementos que correspondem àqueles onde a matriz `indices_booleans` é `True`.

Outra coisa que podemos ver é que ele apenas manteve os elementos pares, então agora veremos como manter os elementos pares de uma matriz, sem ter que fazê-lo à mão, como fizemos no exemplo anterior.

In [ ]:
arr = np.array([[1, 2, 3, 4, 5], 
                [6, 7, 8, 9, 10]])
 
indices_booleanos = arr % 2 == 0
 
arr_filter = arr[indices_booleanos]
 
print(f"Array original: {arr}\n")
print(f"indices booleanos: {indices_booleanos}\n")
print(f"Array filtrado: {arr_filter}")

Array original: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

indices booleanos: [[False  True False  True False]
 [ True False  True False  True]]

Array filtrado: [ 2  4  6  8 10]
